//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StArray.Agent.Functions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StArray.Agent.Functions.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一个整数.
        /// </summary>
        internal static string Param_A {
            get {
                return ResourceManager.GetString("Param_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二个整数.
        /// </summary>
        internal static string Param_B {
            get {
                return ResourceManager.GetString("Param_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待分析的源代码.
        /// </summary>
        internal static string Param_Code {
            get {
                return ResourceManager.GetString("Param_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要写入的内容.
        /// </summary>
        internal static string Param_Content {
            get {
                return ResourceManager.GetString("Param_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期字符串.
        /// </summary>
        internal static string Param_Date {
            get {
                return ResourceManager.GetString("Param_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要增加的天数.
        /// </summary>
        internal static string Param_Days {
            get {
                return ResourceManager.GetString("Param_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待验证的 JSON 字符串.
        /// </summary>
        internal static string Param_Json {
            get {
                return ResourceManager.GetString("Param_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件路径.
        /// </summary>
        internal static string Param_Path {
            get {
                return ResourceManager.GetString("Param_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本输入.
        /// </summary>
        internal static string Param_Text {
            get {
                return ResourceManager.GetString("Param_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一个文本.
        /// </summary>
        internal static string Param_Text1 {
            get {
                return ResourceManager.GetString("Param_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二个文本.
        /// </summary>
        internal static string Param_Text2 {
            get {
                return ResourceManager.GetString("Param_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计源代码行数.
        /// </summary>
        internal static string Tool_Code_CountLines {
            get {
                return ResourceManager.GetString("Tool_Code_CountLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证 JSON 字符串.
        /// </summary>
        internal static string Tool_Code_ValidateJson {
            get {
                return ResourceManager.GetString("Tool_Code_ValidateJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查指定路径的文件是否存在.
        /// </summary>
        internal static string Tool_File_Exists {
            get {
                return ResourceManager.GetString("Tool_File_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取文件全部文本.
        /// </summary>
        internal static string Tool_File_ReadAllText {
            get {
                return ResourceManager.GetString("Tool_File_ReadAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将文本内容写入文件.
        /// </summary>
        internal static string Tool_File_WriteAllText {
            get {
                return ResourceManager.GetString("Tool_File_WriteAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两个整数相加.
        /// </summary>
        internal static string Tool_Math_Add {
            get {
                return ResourceManager.GetString("Tool_Math_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一个数除以第二个数.
        /// </summary>
        internal static string Tool_Math_Divide {
            get {
                return ResourceManager.GetString("Tool_Math_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 两个整数相乘.
        /// </summary>
        internal static string Tool_Math_Multiply {
            get {
                return ResourceManager.GetString("Tool_Math_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一个整数减去第二个整数.
        /// </summary>
        internal static string Tool_Math_Subtract {
            get {
                return ResourceManager.GetString("Tool_Math_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拼接两个文本字符串.
        /// </summary>
        internal static string Tool_Text_Concat {
            get {
                return ResourceManager.GetString("Tool_Text_Concat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取文本字符串的长度.
        /// </summary>
        internal static string Tool_Text_Length {
            get {
                return ResourceManager.GetString("Tool_Text_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将文本转换为小写.
        /// </summary>
        internal static string Tool_Text_ToLower {
            get {
                return ResourceManager.GetString("Tool_Text_ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将文本转换为大写.
        /// </summary>
        internal static string Tool_Text_ToUpper {
            get {
                return ResourceManager.GetString("Tool_Text_ToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 给日期增加指定天数.
        /// </summary>
        internal static string Tool_Time_AddDays {
            get {
                return ResourceManager.GetString("Tool_Time_AddDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取当前本地时间.
        /// </summary>
        internal static string Tool_Time_Now {
            get {
                return ResourceManager.GetString("Tool_Time_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取当前 UTC 时间.
        /// </summary>
        internal static string Tool_Time_UtcNow {
            get {
                return ResourceManager.GetString("Tool_Time_UtcNow", resourceCulture);
            }
        }
    }
}
