using Microsoft.Extensions.AI;

namespace StArray.Agent.Functions.Core;

/// <summary>
/// 提供从所有 <see cref="ITools"/> 实现创建 AIFunction 的工厂。
/// 静态属性和 CreateAll / GetAllFunctions 方法由源生成器自动生成。
/// 静态属性和 GetAllFunctions 方法由源生成器自动生成。
/// Static properties and GetAllFunctions are auto-generated by the source generator.
/// </summary>
public static partial class FunctionFactory
{
    /// <summary>
    /// 由源生成器实现：遍历所有 ITools 实例返回其 AIFunction。
    /// Implemented by source generator: iterates all ITools instances and returns their AIFunction.
    /// </summary>
    public static partial IEnumerable<AIFunction> GetAllFunctions();
}